### ISSUE TITLE
Transfer & refactor initial code from ixmp.reporting

### ISSUE THREAD

**Issue by khaeru** [khaeru/genno#1]
- [x] Filter `ixmp` commits for only those that affect reporting code —done in #2
- [x] Set up packaging —#3
  - [x] setup.{py,cfg}
  - [x] Documentation using Sphinx
- [x] Set up CI using GitHub Actions
  - [x] lint.yml —#3
  - [x] pytest.yml —#7
  - [x] Add badge
- [x] Ensure tests all pass —#3
- [x] Reorganized code into a coherent structure —#3
- [x] Set up RTD and add badge —#7
- [x] Set up Codecov and add badge —#7
